<a href="https://colab.research.google.com/github/wesleyc00/analise-de-dados/blob/main/python_p_analise_dados_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
# Importar a lib

import numpy as np

In [20]:
# Versão
print(np.__version__)

1.26.4


In [22]:
# Criar uma matriz

Array = np.array([1,2,3])

print(Array)

[1 2 3]


In [23]:
# Tipo
type(Array)

numpy.ndarray

In [26]:
# 2D Array

Array2 = np.array([
    [1,2,3],
    [4,5,6]])

print(Array2)

[[1 2 3]
 [4 5 6]]


In [29]:
# 3D Array

Array3 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(Array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
# Experimento de processamento

Estressando_np = np.arange(10000000)
len(Estressando_np)

10000000

In [39]:
# 1º Teste

%time for loop in Estressando_np: pass

CPU times: user 851 ms, sys: 0 ns, total: 851 ms
Wall time: 854 ms


In [42]:
# Acessar os arrays
#1ª Posição
Array[0]

1

In [43]:
# Ultima

Array[-1]

3

In [44]:
# Range

Array[0:2]

array([1, 2])

In [45]:
# Operações

Array[0] + Array[1]

3

In [46]:
# Subtração

Array[0] - Array[1]

-1

In [47]:
# Multiplicar

Array[0] * Array[1]

2

In [48]:
# Dividir

Array[0] / Array[1]

0.5

In [49]:
# Bool

Array[0] > Array[1]

False

In [50]:
# Bool

Array[0] < Array[1]

True

In [51]:
# Verificar dimensoes

Array.shape

(3,)

In [52]:
# 2D

Array2.shape

(2, 3)

In [53]:
# 3D

Array3.shape

(3, 4)

In [54]:
# Loop

for x in Array:
    print(x)

1
2
3


In [55]:
# Loop 2D

for x in Array2:
    print(x)

[1 2 3]
[4 5 6]


In [57]:
import pandas as pd

In [60]:
# Visualização com Pandas

pd.DataFrame(Array3)

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12